src/NbaRosManagementTool/Models/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NbaRosManagementTool.Models
{
    public class Team
    {
        public int ID { get; set; }

        public string CityName { get; set; }

        public string TeamName { get; set; }

        public decimal TeamPayroll { get; set; }

        public decimal CapSpace { get; set; }

        public List<Player> Roster { get; set; }

    }
}

src/NbaRosManagementTool/ViewModels/InitialLoginViewModel.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using NbaRosManagementTool.Models;
using NbaRosManagementTool.Data;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace NbaRosManagementTool.ViewModels
{
    public class InitialLoginViewModel
    {
        [Required]
        [Display(Name = "Teams")]
        public int TeamID { get; set; }

        private readonly NbaDbContext context;

        public List<SelectListItem> TeamList { get; set; }

        public List<Player> PlayerList { get; set; }

        public Team theTeam { get; set; }

        public List<Player> userPlayerList { get; set; }

        public UserTeams theUserTeam { get; set; }

        public InitialLoginViewModel() { }

        public InitialLoginViewModel(IEnumerable<Team> teams, NbaDbContext dbContext,int id)
        {

            context = dbContext;
            TeamList = new List<SelectListItem>();
            TeamID = id;
            theTeam = context.Teams.Single(t => t.ID == id);
            

            foreach (Team teamItems in teams)
            {
                String url = String.Format("/InitialLogin/Team/?id={0}", teamItems.ID);
                TeamList.Add(new SelectListItem
                {
                    Value = url,
                    Text = teamItems.CityName + " " + teamItems.TeamName
                });

            }
            
         
            //remove free agents from list 
            TeamList.RemoveAt(TeamList.Count() - 1);
        }

        public List<Player> getPlayers(int teamID)
        {
            PlayerList = new List<Player>();
            PlayerList = context.Players.Where(p => p.TeamID == teamID).ToList();
            return PlayerList;
        }
     }
}

src/NbaRosManagementTool/Controllers/InitialLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NbaRosManagementTool.Data;
using Microsoft.AspNetCore.Mvc;
using NbaRosManagementTool.ViewModels;
using NbaRosManagementTool.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using static NbaRosManagementTool.Models.ApplicationUser;
using System.Security.Claims;

namespace NbaRosManagementTool.Controllers
{
    public class InitialLoginController : Controller
    {
        private readonly NbaDbContext context;
        private readonly UserManager<ApplicationUser> _userManager;
        
     


        public InitialLoginController(NbaDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            context = dbContext;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            ClaimsPrincipal currentUser = this.User;
            var user = await _userManager.GetUserAsync(currentUser);

            UserTeams userTeam = new UserTeams();
            
            //route user to their team if they have one 
            try
            {
                userTeam = context.UserTeams.Single(t => t.User == user);
            }
            catch (InvalidOperationException e)
            {
                InitialLoginViewModel initialLoginViewModel = new InitialLoginViewModel();
                return View(initialLoginViewModel);

            }
            String url = String.Format("/InitialLogin/Team/?id=1");
            return Redirect(url);
           
            
        }

        [HttpPost]
        public async Task<IActionResult> Team(string cityName, string teamName,int id)
        {
            UserTeams userTeam = new UserTeams(cityName, teamName);
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var theUserID = claim.Value;
            var currentUser = await _userManager.FindByIdAsync(theUserID);

            //initial user setup 
            userTeam.User = currentUser;
            userTeam.UserName = currentUser.UserName;
            context.UserTeams.Add(userTeam);
            context.SaveChanges();
            List<Team> teams = context.Teams.ToList();
            InitialLoginViewModel initialLoginViewModel = new InitialLoginViewModel(teams, context,id);
            initialLoginViewModel.theUserTeam = userTeam;
            initialLoginViewModel.userPlayerList = new List<Player>();
            return View(initialLoginViewModel);


        }

        public IActionResult Team(int id,string error="")
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var theUserID = claim.Value;
         
            
            List<Team> teams = context.Teams.ToList();
            InitialLoginViewModel initialLoginViewModel = new InitialLoginViewModel(teams, context, id);
            initialLoginViewModel.theUserTeam = new UserTeams();
            initialLoginViewModel.userPlayerList = new List<Player>();

            //get players that belong to user
            initialLoginViewModel.theUserTeam = context.UserTeams.Single(u => u.User.Id == theUserID);
            List<UserPlayers> players = context.UserPlayers.Where(p => p.UserTeamsID == initialLoginViewModel.theUserTeam.ID).ToList();

            //load players in list
            foreach(UserPlayers p in players)
            {
                initialLoginViewModel.userPlayerList.Add(context.Players.Single(pl => pl.ID == p.PlayerID));
            }

            ViewBag.error = error;
            return View(initialLoginViewModel);
        }

        [HttpPost]
        public IActionResult Add(int[] players,int userTeamID,InitialLoginViewModel initialLoginViewModel)
        {
            int[] playersSelected = players;
            IQueryable<UserPlayers> rosterList;
            initialLoginViewModel.theUserTeam = new UserTeams();
            initialLoginViewModel.theUserTeam = context.UserTeams.Single(u => u.ID == userTeamID);
            initialLoginViewModel.userPlayerList = new List<Player>();

            foreach(int p in playersSelected)
            {
                //test if player is already on team 
                var userPl = context.UserPlayers.Find(p,userTeamID);
                if (userPl == null)
                {
                    rosterList = context.UserPlayers.Where(rosterCount => rosterCount.UserTeamsID == initialLoginViewModel.theUserTeam.ID);
                    if (rosterList.Count() > 14)
                    {
                        string error = "Roster can't exceed 15 players";
                        String url = String.Format("/InitialLogin/Team/?id=1&error={0}", error);
                        return Redirect(url);
                    }

                    UserPlayers userPlayer = new UserPlayers();
                    userPlayer.PlayerID = p;
                    userPlayer.UserTeamsID = initialLoginViewModel.theUserTeam.ID;
                    context.UserPlayers.Add(userPlayer);
                    Player player = context.Players.Single(pl => pl.ID == p);
                    initialLoginViewModel.userPlayerList.Add(player);
                    initialLoginViewModel.theUserTeam.CapSpace = initialLoginViewModel.theUserTeam.CapSpace - player.Salary;
                    initialLoginViewModel.theUserTeam.TeamPayroll = initialLoginViewModel.theUserTeam.TeamPayroll + player.Salary;
                }
                else
                {
                    string error= "Player is already on team";
                    String url = String.Format("/InitialLogin/Team/?id=1&error={0}", error);
                    return Redirect(url);
                }
            }

          
            context.SaveChanges();
            return Redirect("/InitialLogin/Team/?id=1");
       }

        [HttpPost]
        public IActionResult Remove(int[] players,string action,int userTeamID,InitialLoginViewModel initialLoginViewModel)
        {
            int[] playersSelected = players;
            initialLoginViewModel.theUserTeam = new UserTeams();
            initialLoginViewModel.theUserTeam = context.UserTeams.Single(u => u.ID == userTeamID);


            if (action == "release")
            {
                foreach (int p in playersSelected)
                {
                    UserPlayers userPlayers = context.UserPlayers.Find(p,userTeamID);
                    context.UserPlayers.Remove(userPlayers);
                    Player player = context.Players.Single(pl => pl.ID == p);
                    initialLoginViewModel.theUserTeam.CapSpace = initialLoginViewModel.theUserTeam.CapSpace + player.Salary;
                    initialLoginViewModel.theUserTeam.TeamPayroll = initialLoginViewModel.theUserTeam.TeamPayroll - player.Salary;
                    if (player.TeamID == 32)
                    {
                        FreeAgent freeAgent = new FreeAgent();
                        freeAgent.FirstName = player.FirstName;
                        freeAgent.LastName = player.LastName;
                        freeAgent.PlayerRating = player.PlayerRating;
                        freeAgent.TeamID = 32;
                        context.FreeAgent.Add(freeAgent);
                        context.Players.Remove(player);
                    }
                }
            }
            else
            {
                String url = String.Format("/User/Team?id={0}", userTeamID);
                return Redirect(url);
               
            }

            context.SaveChanges();
            return Redirect("/InitialLogin/Team/?id=1");
        }

















    }
}

src/NbaRosManagementTool/Views/InitialLogin/Add.cshtml
@{
    ViewData["Title"] = "My team";
}

<h1>Just a test</h1>




<p>List of numbers</p>

src/NbaRosManagementTool/Views/InitialLogin/Index.cshtml
@model NbaRosManagementTool.ViewModels.InitialLoginViewModel
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

@{
    //blank for now 
}

<h2>Create Team Name</h2>
<form asp-controller="InitialLogin" asp-action="Team" method="post">
    <div class="form-group">
        <label for="cityName">City Name</label>
        <input type="text" class="form-control" id="cityName"name="cityName">
    </div>
    <div class="form-group">
        <label for="teamName">Team Name</label>
        <input type="text" class="form-control" id="teamName"name="teamName">
    </div>
    <input type="submit" value="Submit Team">
    <input type="hidden"name="id"value="1" />
</form>

src/NbaRosManagementTool/Views/InitialLogin/Team.cshtml
@model NbaRosManagementTool.ViewModels.InitialLoginViewModel
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

@{
    ViewData["Title"] = "Choose your players";
    Model.PlayerList = Model.getPlayers(Model.TeamID);
}


    <h2>Choose your players.</h2>
    <label asp-for="TeamID"></label>
    <select asp-for="TeamID" asp-items="Model.TeamList" onchange="javascript: location.href = this.value;">
        <option selected="selected">
            @Model.theTeam.CityName @Model.theTeam.TeamName
        </option>
    </select>
    <span asp-validation-for="TeamID"></span>
    <form asp-controller="InitialLogin" asp-action="Add" method="post">
        <h2>@Model.theTeam.CityName @Model.theTeam.TeamName Roster</h2>

        <table class="table-bordered table-striped no-transparent rlstable">
            <tbody>
                <tr>
                    <th>Team Roster</th>
                </tr>
                <tr>
                    <th>Player</th>
                    <th class="col-lg-3">Player Rating</th>
                    <th class="col-lg-4">Salary</th>
                </tr>
                @foreach (Player p in Model.PlayerList)
                {
                    <tr>
                        <td>@p.FirstName @p.LastName</td>
                        <td class="col-lg-3 center">@p.PlayerRating</td>
                        <td class="center">@p.Salary</td>
                        <td><input type="checkbox" id="@p.ID" name="players" value="@p.ID" /></td>
                    </tr>
                }
            </tbody>
        </table>
        <input type="hidden" id="@Model.theUserTeam.ID" name="userTeamID" value="@Model.theUserTeam.ID" />
        <input type="submit" value="Add Player(s)" /><p class="error">@ViewBag.error</p>
    </form>
<div class="level">
    <form asp-controller="InitialLogin" asp-action="Remove" method="post">

        <h2>My Team - @Model.theUserTeam.CityName @Model.theUserTeam.TeamName</h2>
        <table class="table-bordered table-striped no-transparent rlstable">
            <tbody>
                <tr>
                    <th>Team Roster</th>
                </tr>
                <tr>
                    <th>Player</th>
                    <th class="col-lg-3">Player Rating</th>
                    <th class="col-lg-4">Salary</th>
                </tr>
                @foreach (Player p in Model.userPlayerList)
                {
                    <tr>
                        <td>@p.FirstName @p.LastName</td>
                        <td class="col-lg-3 center">@p.PlayerRating</td>
                        <td class="center">@p.Salary</td>
                        <td><input type="checkbox" id="@p.ID" name="players" value="@p.ID" /></td>
                    </tr>
                }
                @for (int i = 0; i < 15 - Model.userPlayerList.Count; i++)
                {
                    <tr>
                        <td>-</td>
                        <td class="col-lg-3">-</td>
                        <td>-</td>
                    </tr>
                }
                <tr>
                    <th>Salary Cap</th>
                    <th class="col-lg-3">Cap space</th>
                    <th class="col-lg-4">Total Salaries</th>
                </tr>
                <tr>
                    <td>105,000,000</td>
                    @if (@Model.theUserTeam.CapSpace > 0)
                    {
                        <td class="col-lg-3 green ">@Model.theUserTeam.CapSpace</td>
                    }
                    else
                    {
                        <td class="col-lg-3 in_the_red ">@Model.theUserTeam.CapSpace</td>
                    }

                    <td>@Model.theUserTeam.TeamPayroll</td>
                </tr>
            </tbody>
        </table>
        <input type="hidden" id="@Model.theUserTeam.ID" name="userTeamID" value="@Model.theUserTeam.ID" />
        <button type="submit" name="action" value="release">Release Player(s)</button>
        <h4>Best teams list rules</h4>
        <p>-Roster has to have minimum of 13 players, 15 max.</p>
        <p>-Total salary must be under cap to submit team.</p>
    </form>
</div>